### ISSUE TITLE
areAllMsgDifferent in aggregateVerify

### ISSUE THREAD

**Issue by dapplion** [herumi/bls-eth-wasm#10]
According to the bls signature spec it is not necessary to check that all messages are different
https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-04

Is there any good reason to check that here or it's just an extra test?
https://github.com/herumi/bls-eth-wasm/blob/335293055e185b78e35687f137c397da499b61c3/test/test.js#L388
In a production usage of your library should messages by checked with `areAllMsgDifferent` in order for `aggregateVerify` to work properly?

**Comment by herumi** [comment]
|irtf|my bls|
|-|-|
|CoreAggregateVerify|aggregateVerifyNoCheck|
|AggregateVerify|areAllMsgDifferent+aggregateVerifyNoCheck|

https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-04#section-3.1.1
>3.1.1.  AggregateVerify
>
>  This function first ensures that all messages are distinct, and then
>   invokes CoreAggregateVerify.

So, if your application requires only `CoreAggregateVerify` then `areAllMsgDDifferent` is not necessary.
