### ISSUE TITLE
Support/Examples for API for k-of-n threshold signature

### ISSUE THREAD

**Issue by faustbrian** [herumi/bls-eth-wasm#16]
This library relies on https://github.com/herumi/bls-eth-wasm which in turn relies on https://github.com/herumi/bls which has support for threshold signatures via https://github.com/herumi/bls#api-for-k-of-n-threshold-signature.

I guess right now you would rely on https://github.com/herumi/bls-eth-wasm exposing those methods so you could access them or are there any plans on adding support/examples for threshold signatures in any another way? Maybe it is already possible to verify an aggregated signature against a subset of public keys and I overlooked it. The use-case would be an M-of-N MuSig implementation where any M signatures being valid according to a set of N public keys results in the verification of an aggregated signature passing.

> Copy of https://github.com/ChainSafe/bls/issues/120

**Comment by herumi** [comment]
I'm sorry that I don't understand what you want.
bls-eth-wasm already provides an example for k-of-n threshold signature.
https://github.com/herumi/bls-eth-wasm/blob/master/test/test.js#L154

**Comment by faustbrian** [comment]
Thanks, overlooked that test 😅 What I'm specifically looking for is the following for an M-of-N MuSig _(or K-of-N as called here)_

1. A **subgroup** of a group of participants sign a message without knowing each other private keys.
2. Their signatures are **aggregated** into one.
3. The **aggregated** signature is verified by using:
	- the **aggregated** signature
	- the **aggregated** public key of the subgroup (who really signed)
	- the **aggregated** public key of all participants in the group (whether signed or not)

**Comment by herumi** [comment]
I'm sorry for the late response.
Do you need samples of DKG (Distributed Key Generation) and VSS (Verifiable Secret Sharing)?
If so, then it is out of scope of my library and could you see https://github.com/dfinity-side-projects/dkg , https://github.com/dfinity-side-projects/vss ( these libraries are old and they may need modification) ?

**Comment by faustbrian** [comment]
https://github.com/dfinity-side-projects/dkg looks like what I was looking for, thanks!
