### ISSUE TITLE
multi exponentiations

### ISSUE THREAD

**Issue by atomictag** [herumi/bls-eth-wasm#21]
In my research project I am using both the bls-eth-wasm library and the mcl-wasm one (thank you for the awesome work) to implement various algorithms. There are just a couple of functionality I need from bls-eth-wasm that are not exposed by the mcl library (namely share / recovery of keys). Since the bls-eth-wasm includes (and exports) the mcl lib I have temporarily built an extension that essentially exposes both BLS and MCL stuff from the same wasm in bls_c.js and everything works fine.

However `mcl.mulVec` exported by the wasm in bls_c.js does not work properly - and it crashes (with no error reported) when the size of the vectors is 16 and > 25 (it works in all other cases). The exact same happens for `_blsPublicKeyMulVec` etc. (which I guess are built on the corresponding `_mclBn*_mulVec` primitives). If I use the mcl-wasm library directly everything works fine - so my guess is that the 2 wasm files are built either from different mcl sources or with different compiler options that somehow break this functionality.

After using both bls-eth-wasm and mcl-wasm for some time I came to the realization 99% of the functionality in bls-eth-wasm can be produced with the mcl library but for evaluations and interpolations for key sharing (which are very important for my use cases), so I am not ready yet to switch to mcl-wasm - and it would be really nice if multi-exponentiations would work.

Many thanks!

**Comment by herumi** [comment]
Internally, bls-wasm has all the functionality of mcl-wasm, so we can just export it.
I really want to integrate it, but I haven't been able to do so due to a lack of time.
The mulVec takes up a large stack.
I think it would be better if you specify
EMCC_OPT+=-s STACK_SIZE=1MB
in Makefile.
https://github.com/herumi/mcl-wasm/blob/master/Makefile#LL15C1-L15C28

**Comment by herumi** [comment]
>but for evaluations and interpolations for key sharing (which are very important for my use cases), so I am not ready yet to switch to mcl-wasm.

I see. I'll export the API of share and recover to mcl-wasm.

**Comment by herumi** [comment]
[mcl-wasm](https://github.com/herumi/mcl-wasm) supports share/recover functions.
https://github.com/herumi/mcl-wasm/blob/master/test/test-ts.ts#L568
Note that the order of arguments is reversed from that of the recover function in bls-eth-wasm.
