### ISSUE TITLE
Incorrect packages.json configuration

### ISSUE THREAD

**Issue by tagbug** [herumi/bls-eth-wasm#24]
In the latest npm package bls-eth-wasm@1.2.0, index-browser.js has been removed, but the corresponding packages.json has not been modified in time, causing the reference to not be parsed normally.
But I noticed that the latest commit record was submitted within a few hours. I wonder if you are doing some upgrades or repairs?
I'm sorry if it bothered you and thank you for your efforts.

**Comment by herumi** [comment]
Thank you for the quick verification. I've updated my package to v1.2.1. Would you mind trying it?

**Comment by herumi** [comment]
Thank you for the advice. I could not unpublish it, so I deprecated it.
