### ISSUE TITLE
Proposal to change js repo setup

### ISSUE THREAD

**Issue by dapplion** [herumi/bls-eth-wasm#4]
I'm opening this issue to know your opinion on changing the js repo structure. First, note that I will do all the changes myself and no action is needed from your side; more than being okay with the idea so I can move forward. 

#### Changes
The current setup is suboptimal for the reasons outlined on each change item. Please express if all the changes below are of interest or if only a subset of them:

- Change `bls.js` self-executing function to a regular export pattern like `bls_c.js`.
  - Why? It does not allow to customize the loading behavior of the WASM file. To distribute an NPM library with the WASM it best to inline the source and this is not currently possible
- Migrate `bls.js` to Typescript, which has very similar semantics to C++ and would provide static type-safety downstream
  - Why? Adding types downstream risks of breaking changes slipping through. While Emscripten doesn't out TS types by default this is the safest solution.
- Divide monolithic `bls.js` file code into multiple files; i.e. one per class, a utils file, and an index
  - Why? Easier to maintain and reason about.

The above changes will allow the library to be easily demo-able in a standalone .HTML file + be consumable downstream without adding unnecessary complexity.

**Comment by herumi** [comment]
Thank you for the proposal.

>To distribute an NPM library with the WASM it best to inline the source and this is not currently possible

Is there an easy-to-read sample?

>Migrate bls.js to Typescript, which has very similar semantics to C++ and would provide static type-safety downstream

I see. I'm not familiar with TypeScript, so I'll start study it.

**Comment by dapplion** [comment]
> Is there an easy-to-read sample?
As an example you can check this setup.
1) Add an import directive with the wasm file [bls-eth-wasm/bls.js#L1](https://github.com/ChainSafe/eth2-bls-wasm/blob/3e6f36d84dee66e35b21c4a26ff5430404ceea4b/bls-eth-wasm/bls.js#L1)
```ts
import wasmCode from './bls_c.wasm';
```
2) Use a javascript bundler `babel` that converts the import directive into a serialization of the target file contents [.babelrc#L17](https://github.com/ChainSafe/eth2-bls-wasm/blob/3e6f36d84dee66e35b21c4a26ff5430404ceea4b/.babelrc#L17)
```
"plugins": [
    ["@chainsafe/babel-plugin-inline-binary-import", {
      "extensions": [
        ".wasm"
      ]
    }]
  ]
```
The resulting file will look like this
```ts
/* babel-plugin-inline-binary-import './bls_c.wasm' */
const wasmCode = "\0asm\x01\0\0\0\x01\xA1\x01\x16`\x04\x7F\x7F\x7F\x ......
```

-----

Let me know if that answers your question

**Comment by herumi** [comment]
Does babel import bls_c.wasm into bls.js? How is bls_c.js treated?

**Comment by dapplion** [comment]
Note that this is a particular setup example. In the example, I'm stating above:
- babel inlines `bls_c.wasm` into `bls.js`
- `bls_c.js` is left as-is and can be imported from the `bls.js` if it's not already in the window scope (for browsers)

`bls_c.js` has already a somewhat versatile export strategy so it's available both in the window global scope and to be imported in NodeJS with `require()`

**Comment by dapplion** [comment]
That boilerplate probably gets added automatically by `emcc` thanks to the option
```
-s MODULARIZE=1
```

From this issue https://github.com/emscripten-core/emscripten/issues/10114#issuecomment-569445272 you can also use the option
```
-s EXPORT_ES6=1
```
which uses modern ES6 syntax to define the module export
